-- ============================================================
--  lib/supabase-apply-all.sql
--  Combined Supabase schema — generated by codebuff apply-up pipeline.
--  Run this ONCE in your Supabase SQL Editor (Dashboard > SQL Editor > New query).
--  Idempotent: every CREATE TABLE uses IF NOT EXISTS. Every CREATE POLICY is
--  preceded by DROP POLICY IF EXISTS so the file is safe to re-run if it
--  previously failed mid-stream.
--  Total migrations: 16
--  Source files: lib/supabase-migration.sql, lib/supabase-fix-habits-migration.sql, lib/supabase-user-profile-migration.sql, lib/supabase-orion-redesign-migration.sql, lib/supabase-physique-migration.sql, lib/supabase-physique-photos-fix-migration.sql, lib/supabase-physique-albums-migration.sql, lib/supabase-physique-favourites-migration.sql, lib/supabase-fitness-migration.sql, lib/supabase-gym-migration.sql, lib/supabase-workout-summary-migration.sql, lib/supabase-health-migration.sql, lib/supabase-tasks-migration.sql, lib/supabase-finance-migration.sql, lib/supabase-future-transactions-migration.sql, lib/supabase-time-management-migration.sql
-- ============================================================


-- ──── lib\supabase-migration.sql ────

-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)

-- 1. Tags table
CREATE TABLE IF NOT EXISTS tags (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  user_id UUID DEFAULT auth.uid(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Seed some default tags
INSERT INTO tags (name, color) VALUES
  ('Health', 'bg-emerald-100 text-emerald-700 border-emerald-200'),
  ('Mind', 'bg-sky-100 text-sky-700 border-sky-200'),
  ('Work', 'bg-violet-100 text-violet-700 border-violet-200'),
  ('Fitness', 'bg-cyan-100 text-cyan-700 border-cyan-200');

-- 2. Add columns to existing habits table
ALTER TABLE habits ADD COLUMN IF NOT EXISTS custom_frequency TEXT DEFAULT '';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS tag_id UUID REFERENCES tags(id);
ALTER TABLE habits ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT auth.uid();

-- Drop the old simple columns since we're replacing them
ALTER TABLE habits DROP COLUMN IF EXISTS completed;
ALTER TABLE habits DROP COLUMN IF EXISTS tag;

-- Make frequency non-nullable with default
ALTER TABLE habits ALTER COLUMN frequency SET DEFAULT 'daily';
UPDATE habits SET frequency = 'daily' WHERE frequency IS NULL;
ALTER TABLE habits ALTER COLUMN frequency SET NOT NULL;

-- 3. Habit completions table (date-based tracking)
CREATE TABLE IF NOT EXISTS habit_completions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  habit_id UUID REFERENCES habits(id) ON DELETE CASCADE NOT NULL,
  completed_date DATE NOT NULL,
  user_id UUID DEFAULT auth.uid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(habit_id, completed_date)
);

-- 4. Enable Row Level Security (optional, open access for now)
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_completions ENABLE ROW LEVEL SECURITY;

-- 5. Events table (extensible audit log for AI agent & analytics)
CREATE TABLE IF NOT EXISTS events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at);
CREATE INDEX IF NOT EXISTS idx_events_user_id ON events(user_id);

-- 6. Enable RLS on events
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Drop old public-access policies before creating user-scoped ones
DROP POLICY IF EXISTS "Public access" ON tags;
DROP POLICY IF EXISTS "Public access" ON habits;
DROP POLICY IF EXISTS "Public access" ON habit_completions;
DROP POLICY IF EXISTS "Public access" ON events;

-- User-scoped RLS policies (rows must belong to the authenticated user)
-- Tags allow NULL user_id (seeded/default tags visible to everyone).
DROP POLICY IF EXISTS "User owns data" ON tags;
CREATE POLICY "User owns data" ON tags
  FOR ALL USING (auth.uid() = user_id OR user_id IS NULL)
  WITH CHECK (auth.uid() = user_id);

-- Habits, completions, and events are strictly scoped to the owning user.
DROP POLICY IF EXISTS "User owns data" ON habits;
CREATE POLICY "User owns data" ON habits
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON habit_completions;
CREATE POLICY "User owns data" ON habit_completions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON events;
CREATE POLICY "User owns data" ON events
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ──── lib\supabase-fix-habits-migration.sql ────

-- ============================================================
-- FIX: Missing columns & RLS policies for Habits & Tags tables
-- ============================================================
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
--
-- Diagnosis: The tables tags, habits, and habit_completions exist
-- but are MISSING the user_id column. This causes errors like:
--   "column habit_completions.user_id does not exist"
--
-- The original migration was partially applied (tables were created
-- with basic columns), but the ALTER TABLE statements and RLS policies
-- were never executed.
-- ============================================================

-- ============================================================
-- 1. Add missing user_id columns to existing tables
-- ============================================================
ALTER TABLE tags
  ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT auth.uid();

ALTER TABLE habits
  ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT auth.uid();

ALTER TABLE habit_completions
  ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT auth.uid();

-- Verify: run this to confirm columns were added
-- SELECT column_name FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'habit_completions'
--   ORDER BY ordinal_position;

-- ============================================================
-- 2. Create events table if it doesn't exist
-- ============================================================
CREATE TABLE IF NOT EXISTS events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at);
CREATE INDEX IF NOT EXISTS idx_events_user_id ON events(user_id);

-- ============================================================
-- 3. Add UNIQUE constraint to habit_completions if missing
-- ============================================================
-- Drop any existing constraint first, then re-add it safely
ALTER TABLE habit_completions DROP CONSTRAINT IF EXISTS habit_completions_habit_id_completed_date_key;

-- Drop any existing duplicate rows (keep the earliest)
DELETE FROM habit_completions a
  USING habit_completions b
  WHERE a.id < b.id
    AND a.habit_id = b.habit_id
    AND a.completed_date = b.completed_date;

-- Add the unique constraint
ALTER TABLE habit_completions
  ADD CONSTRAINT habit_completions_habit_id_completed_date_key
  UNIQUE (habit_id, completed_date);

-- ============================================================
-- 4. Fix RLS policies
-- ============================================================

-- Enable RLS on all tables (safe to re-run)
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Drop ALL existing policies to start fresh
DROP POLICY IF EXISTS "Public access" ON tags;
DROP POLICY IF EXISTS "Public access" ON habits;
DROP POLICY IF EXISTS "Public access" ON habit_completions;
DROP POLICY IF EXISTS "Public access" ON events;
DROP POLICY IF EXISTS "User owns data" ON tags;
DROP POLICY IF EXISTS "User owns data" ON habits;
DROP POLICY IF EXISTS "User owns data" ON habit_completions;
DROP POLICY IF EXISTS "User owns data" ON events;

-- Create user-scoped RLS policies
-- Tags allow NULL user_id (seeded/default tags visible to everyone).
DROP POLICY IF EXISTS "User owns data" ON tags;
CREATE POLICY "User owns data" ON tags
  FOR ALL USING (auth.uid() = user_id OR user_id IS NULL)
  WITH CHECK (auth.uid() = user_id);

-- Habits, completions, and events are strictly scoped to the owning user.
DROP POLICY IF EXISTS "User owns data" ON habits;
CREATE POLICY "User owns data" ON habits
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON habit_completions;
CREATE POLICY "User owns data" ON habit_completions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON events;
CREATE POLICY "User owns data" ON events
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- 5. Seed default tags if tags table is empty
-- ============================================================
INSERT INTO tags (name, color)
SELECT name, color
FROM (VALUES
  ('Health', 'bg-emerald-100 text-emerald-700 border-emerald-200'),
  ('Mind', 'bg-sky-100 text-sky-700 border-sky-200'),
  ('Work', 'bg-violet-100 text-violet-700 border-violet-200'),
  ('Fitness', 'bg-cyan-100 text-cyan-700 border-cyan-200')
) AS seed(name, color)
WHERE NOT EXISTS (
  SELECT 1 FROM tags t WHERE t.name = seed.name
);

-- ============================================================
-- 6. Verify the fix
-- ============================================================
-- Run this in the SQL Editor after the script completes:
--
-- SELECT table_name, column_name, data_type
-- FROM information_schema.columns
-- WHERE table_schema = 'public'
--   AND table_name IN ('tags', 'habits', 'habit_completions', 'events')
--   AND column_name = 'user_id'
-- ORDER BY table_name;
--
-- Expected: 4 rows (one per table), each showing user_id column exists.


-- ──── lib\supabase-user-profile-migration.sql ────

-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- Adds a user_profiles table for storing shared user settings like birth_date.

-- 1. User profiles table
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id UUID DEFAULT auth.uid() PRIMARY KEY,
  birth_date DATE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Enable RLS
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- 3. Drop old policies before creating new ones
DROP POLICY IF EXISTS "User owns profile" ON user_profiles;

-- 4. RLS policy — each user can only access their own profile
DROP POLICY IF EXISTS "User owns profile" ON user_profiles;
CREATE POLICY "User owns profile" ON user_profiles
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ──── lib\supabase-orion-redesign-migration.sql ────

-- ================================================================
-- ORION Health Redesign Migration — Speed & Insight
-- ================================================================
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
--
-- Changes:
-- 1. NEW: training_logs — simplified workout logging (type, exercise, weight, reps, RPE)
-- 2. ALTER: nutrition_logs — add calories, protein_g columns
-- 3. NEW: recovery_logs — replaces manual_inputs for quick recovery logging
-- 4. DROP: focus_level from manual_inputs (simplify)
--
-- All new tables include user_id for RLS scoping.
-- ================================================================

-- ================================================================
-- 1. training_logs — simplified one-row-per-exercise workouts
-- ================================================================
CREATE TABLE IF NOT EXISTS training_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid() NOT NULL,
  workout_type TEXT NOT NULL,          -- free text: 'Upper', 'Push', 'Run', etc.
  exercise TEXT NOT NULL,              -- primary exercise name
  weight_lbs DECIMAL(6,1),            -- best working set weight in lbs (nullable for bodyweight)
  reps INTEGER CHECK (reps IS NULL OR reps > 0),  -- best working set reps
  rpe INTEGER NOT NULL CHECK (rpe >= 1 AND rpe <= 10),  -- perceived effort 1-10
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for time-series queries
CREATE INDEX IF NOT EXISTS idx_training_logs_user ON training_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_training_logs_created_at ON training_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_training_logs_exercise ON training_logs(exercise);
CREATE INDEX IF NOT EXISTS idx_training_logs_workout_type ON training_logs(workout_type);

ALTER TABLE training_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "User owns training data" ON training_logs;
DROP POLICY IF EXISTS "User owns training data" ON training_logs;
CREATE POLICY "User owns training data" ON training_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ================================================================
-- 2. nutrition_logs — add new columns for simplified tracking
-- ================================================================
ALTER TABLE nutrition_logs
  ADD COLUMN IF NOT EXISTS calories INTEGER DEFAULT 0 CHECK (calories >= 0),
  ADD COLUMN IF NOT EXISTS protein_g DECIMAL(6,1) DEFAULT 0 CHECK (protein_g >= 0);

-- The old columns (water_ml, caffeine_mg, caffeine_time, creatine_taken)
-- are kept for backward compatibility with existing data but will no
-- longer be used by the new quick-log flows.

CREATE INDEX IF NOT EXISTS idx_nutrition_logs_calories ON nutrition_logs(calories);

-- ================================================================
-- 3. recovery_logs — energy, stress, soreness quick-log
-- ================================================================
CREATE TABLE IF NOT EXISTS recovery_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid() NOT NULL,
  energy_level INTEGER NOT NULL CHECK (energy_level >= 1 AND energy_level <= 10),
  stress_level INTEGER NOT NULL CHECK (stress_level >= 1 AND stress_level <= 10),
  soreness_level INTEGER NOT NULL CHECK (soreness_level >= 1 AND soreness_level <= 10),
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_recovery_logs_user ON recovery_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_recovery_logs_created_at ON recovery_logs(created_at);

ALTER TABLE recovery_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "User owns recovery data" ON recovery_logs;
DROP POLICY IF EXISTS "User owns recovery data" ON recovery_logs;
CREATE POLICY "User owns recovery data" ON recovery_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ================================================================
-- 4. Simplify manual_inputs — drop focus_level (optional)
-- ================================================================
-- The manual_inputs table is kept (with existing data) but the
-- focus_level column is removed since it's not used in the new
-- recovery flow. If you want to keep historical focus_level data,
-- COMMENT OUT this ALTER statement.
--
-- ALTER TABLE manual_inputs DROP COLUMN IF EXISTS focus_level;

-- ================================================================
-- 5. Update nutrition_logs RLS (already exists from previous migration)
-- ================================================================
-- nutrition_logs RLS is already enabled from the previous health migration.
-- No changes needed unless you see errors about missing policies.

-- ================================================================
-- Verification Queries (run after migration in SQL Editor)
-- ================================================================
--
-- Check tables exist:
-- SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public'
--     AND table_name IN ('training_logs', 'recovery_logs')
--   ORDER BY table_name;
--
-- Check nutrition_logs columns:
-- SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'nutrition_logs'
--   ORDER BY ordinal_position;


-- ──── lib\supabase-physique-migration.sql ────

-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- Creates the "progress-pics" Storage bucket and RLS policies for
-- progress photo uploads via the Physique Tracker.
--
-- NOTE: The physique_logs table already exists from supabase-health-migration.sql.
--       This migration ONLY adds the storage bucket configuration.

-- 1. Create the storage bucket (idempotent — safe to re-run)
INSERT INTO storage.buckets (id, name, public, avif_autodetection, file_size_limit, allowed_mime_types)
VALUES (
  'progress-pics',
  'progress-pics',
  true,                       -- public (we use public URLs for <img> tags)
  false,
  10485760,                   -- 10 MB limit
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']::text[]
)
ON CONFLICT (id) DO NOTHING;

-- 3. Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "Users can upload their own progress photos" ON storage.objects;
DROP POLICY IF EXISTS "Users can view progress photos" ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own progress photos" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own progress photos" ON storage.objects;

-- 4. Policy: any authenticated user can view progress photos (public bucket but scoped)
CREATE POLICY "Users can view progress photos"
ON storage.objects FOR SELECT
USING (bucket_id = 'progress-pics');

-- 5. Policy: users can upload photos — path must start with their own user_id
--    (uploaded path is: user_id/timestamp-filename)
CREATE POLICY "Users can upload their own progress photos"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'progress-pics'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- 6. Policy: users can update their own photos
CREATE POLICY "Users can update their own progress photos"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'progress-pics'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- 7. Policy: users can delete their own photos
CREATE POLICY "Users can delete their own progress photos"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'progress-pics'
  AND (storage.foldername(name))[1] = auth.uid()::text
);


-- ──── lib\supabase-physique-photos-fix-migration.sql ────

-- =====================================================================
-- ORION: Physique photos — schema fix & RLS upsert (deadlock-safe)
-- =====================================================================
-- Apply when:
--   • setSessionCover() (album cover) fails because `cover_photo_id`
--     or `session_title` columns are missing.
--   • UPDATE on physique_photos returns 0 rows (silent RLS denial).
--
-- ─── Why `cover_photo_id` lives on `physique_photos` (denormalized) ───
-- A separate `physique_sessions` table was considered and rejected:
--   • ORION already denormalizes `notes`, `body_weight_kg`,
--     `is_favourited`, `featured_at`, and `session_title` across
--     every photo of the same `taken_at` — sessions are derived from
--     the photo rows themselves, not stored separately.
--   • A dedicated sessions table would require a JOIN on every read
--     (gallery list, dashboard hero pick, compare-sessions, timeline)
--     AND a migration of every existing photo row to backfill a
--     session_id. That's a lot of chURn for ~100 sessions × <10 photos
--     per user (the typical scale).
--   • Cover change is one `UPDATE … WHERE user_id = ? AND taken_at = ?`
--     across the session's rows, all of which already have their
--     own `cover_photo_id`. Storing it as a self-FK inside the same
--     table keeps the session write atomic, observable, and trivially
--     indexed by (user_id, cover_photo_id).
--   • Self-reference (cover points at a member of the same table) is
--     intentional — see the “no self-cover CHECK” note in §3 below.
-- Conclusion: keep the current denormalized design.
--
-- ─── Design notes (this rewrite replaces an earlier version that
--     deadlocked with SQLSTATE 40P01):                         ───
--
--   • NO iteration over pg_policies. The earlier draft looped
--     EXECUTE 'DROP POLICY' over every policy on the table. Inside
--     Supabase's implicit transaction that sequence deadlocked with
--     concurrent lock holders (autovacuum or other clients). This
--     version touches a SINGLE well-known policy and leaves every
--     other policy you defined absolutely intact.
--
--   • NO DO blocks. All DDL is top-level ALTER/CREATE statements
--     with brief share-locks that don't escalate to AccessExclusive.
--
--   • The "User owns physique photos" policy is upserted — single
--     DROP IF EXISTS for the well-known name, followed by a single
--     CREATE with FOR ALL TO authenticated. This guarantees
--     SELECT/INSERT/UPDATE/DELETE all work for the signed-in user.
--
--   • The FK from cover_photo_id back to physique_photos(id) uses
--     ON DELETE SET NULL so deleting a pinned cover cleanly falls
--     back to "first uploaded photo" without leaving dangling refs.
--
--   • We deliberately do NOT add a `cover_photo_id <> id` CHECK.
--     ORION's denormalized session model writes
--       UPDATE physique_photos
--          SET cover_photo_id = :picked_id
--        WHERE user_id = :u AND taken_at = :d
--     across every photo of the session — including the picked
--     photo itself (so its own row reads `cover_photo_id = self.id`,
--     which groupPhotosIntoSessions treats as the "pinned" signal).
-- =====================================================================


-- ─── 1. Columns (idempotent; metadata-only when columns exist) ──
ALTER TABLE physique_photos
  ADD COLUMN IF NOT EXISTS session_title TEXT;

ALTER TABLE physique_photos
  ADD COLUMN IF NOT EXISTS cover_photo_id UUID
    REFERENCES physique_photos(id)
    ON DELETE SET NULL;


-- ─── 2. Cover-resolution lookup index ────────────────────────────
-- Concurrently built the first time; instant no-op on re-run.
CREATE INDEX IF NOT EXISTS idx_physique_photos_cover
  ON physique_photos(user_id, cover_photo_id)
  WHERE cover_photo_id IS NOT NULL;


-- ─── 3. Make sure RLS is on (no-op if already enabled) ──────────
ALTER TABLE physique_photos ENABLE ROW LEVEL SECURITY;


-- ─── 4. Upsert ONLY the canonical policy ─────────────────────────
-- Single DROP for the well-known name, then a single CREATE. Any
-- other policies you defined (e.g. custom team-sharing rules,
-- premium tier visibility) are NOT touched and remain fully armed.
-- ──────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "User owns physique photos" ON physique_photos;

DROP POLICY IF EXISTS "User owns physique photos" ON physique_photos;
CREATE POLICY "User owns physique photos" ON physique_photos
  FOR ALL TO authenticated
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 5. Tell PostgREST to reload its schema cache ────────────────
-- The new column is normally visible in seconds, but a defensive
-- NOTIFY avoids the rare case where the next browser refresh still
-- surfaces a stale 42703. The `pgrst` channel is exposed by
-- Supabase automatically.
--
-- Caveat: NOTIFY only fires when the surrounding transaction
-- COMMITS. If a future regression ever causes this script to
-- rollback at any earlier step (deadlock, FK validation, etc.),
-- this message is silently dropped — the in-script SELECT below
-- is the durable "did the columns land?" answer regardless.
NOTIFY pgrst, 'reload schema';


-- ─── 6. In-script smoke test ─────────────────────────────────────
-- Renders directly in the SQL Editor's "Results" tab so the user
-- sees confirmation in the same page they just ran. Plain SELECT
-- only — no DO block, no DDL, no lock escalation.
SELECT
  column_name,
  data_type,
  is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'physique_photos'
  AND column_name  IN ('session_title', 'cover_photo_id')
ORDER BY column_name;

-- You should see two rows: cover_photo_id (uuid, YES), session_title (text, YES).
-- If a row is missing, the migration was interrupted — re-run it.


-- =====================================================================
-- LATE-CHECK VERIFICATION (run as a SECOND separate New query after
-- this migration commits — also not part of the live script, to
-- keep the lock footprint minimal):
--
--   SELECT policyname, cmd
--     FROM pg_policies
--    WHERE schemaname = 'public'
--      AND tablename  = 'physique_photos';
--   -- You should see "User owns physique photos" with cmd='ALL'
--   -- plus any custom policies you defined.
-- =====================================================================


-- ──── lib\supabase-physique-albums-migration.sql ────

-- =====================================================================
-- ORION: Physique album metadata
-- =====================================================================
-- Adds `session_title` and `cover_photo_id` to `physique_photos`. Both
-- are DENORMALIZED across every photo of a session, matching the
-- existing pattern (notes, body_weight_kg, is_favourited). Reads stay
-- trivially indexed by user_id + taken_at; writes happen as one UPDATE
-- per session (`WHERE user_id = … AND taken_at = …`).
--
-- Required by the album-style gallery redesign:
--   - session_title is the user-given album name ("Summer Bulk", etc.)
--   - cover_photo_id lets the user pin a specific photo as the cover;
--     NULL means "use the first uploaded photo" (groupPhotosIntoSessions
--     fallback)
-- =====================================================================

ALTER TABLE physique_photos
  ADD COLUMN IF NOT EXISTS session_title TEXT,
  ADD COLUMN IF NOT EXISTS cover_photo_id UUID
    REFERENCES physique_photos(id)
    ON DELETE SET NULL;

-- ============================================================================
-- No additional RLS changes: existing policy covers all columns
-- (`USING (user_id = auth.uid())`). New columns inherit that.
-- ============================================================================


-- ──── lib\supabase-physique-favourites-migration.sql ────

-- =====================================================================
-- ORION: Physique Favourites Migration (additive)
-- =====================================================================
-- Apply AFTER supabase-fitness-migration.sql.
-- Adds the star/favourite primitives needed by the new Physique Timeline
-- + Gallery split. Pure additive — won't break any existing rows.
--
--   • is_favourited      — star toggle, drives what shows in Timeline
--   • featured_at        — wall-clock moment of last star (for ordering)
--   • pose_type CHECK    — relaxed to allow custom pose strings
-- =====================================================================

-- ─── 1. Favourited columns ──────────────────────────────────────
ALTER TABLE physique_photos
  ADD COLUMN IF NOT EXISTS is_favourited BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE physique_photos
  ADD COLUMN IF NOT EXISTS featured_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_physique_photos_starred
  ON physique_photos(user_id, is_favourited, taken_at DESC);

CREATE INDEX IF NOT EXISTS idx_physique_photos_user_taken
  ON physique_photos(user_id, taken_at DESC);


-- ─── 2. Relax pose_type CHECK ───────────────────────────────────
-- The old constraint hard-coded ('front','back','side','other'). New
-- upload flow lets users type custom pose labels ('relaxed','flexed',
-- 'competition', etc.). We replace the CHECK with a permissive one
-- (TEXT NULL is fine), and keep the RLS policy intact.
ALTER TABLE physique_photos
  DROP CONSTRAINT IF EXISTS physique_photos_pose_type_check;

ALTER TABLE physique_photos
  ADD CONSTRAINT physique_photos_pose_type_check
    CHECK (pose_type IS NULL OR length(pose_type) <= 32);


-- ─── 3. RLS — already user-scoped, no change ────────────────────
-- Re-stating for documentation; the existing policy from
-- supabase-fitness-migration.sql already covers these columns.


-- ─── 4. Optional: backfill magnet ───────────────────────────────
-- If you previously starred photos in some other tool, populate
-- `featured_at = created_at` so the dashboard hero picks up straight
-- away. Safe to re-run.
UPDATE physique_photos
   SET featured_at = created_at
 WHERE is_favourited = TRUE
   AND featured_at IS NULL;


-- ──── lib\supabase-fitness-migration.sql ────

-- =====================================================================
-- ORION: Fitness migration — long-term progress tracking dashboard
-- =====================================================================
-- Apply AFTER supabase-fix-habits-migration.sql.
-- Tables follow the same `user_id = auth.uid()` RLS pattern as Habits.
-- All workout / photo / weight / sleep / checkin data is private to the
-- signed-in user. PRs are computed client-side in JS (no need for a
-- personal_records table — avoids drift between mutated history and
-- materialised PRs).
-- =====================================================================


-- ─── 1. Exercises (master list of movements) ──────────────────────
CREATE TABLE IF NOT EXISTS exercises (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL DEFAULT auth.uid(),
  name         TEXT NOT NULL,
  category     TEXT,                       -- 'push' / 'pull' / 'legs' / 'core' / 'cardio'
  notes        TEXT,
  is_archived  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_exercises_user_id          ON exercises(user_id);
CREATE INDEX IF NOT EXISTS idx_exercises_user_name_unique ON exercises(user_id, lower(name));

ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns exercises" ON exercises;
DROP POLICY IF EXISTS "User owns exercises" ON exercises;
CREATE POLICY "User owns exercises" ON exercises
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 2. Workouts (a single training session) ───────────────────────
CREATE TABLE IF NOT EXISTS workouts (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL DEFAULT auth.uid(),
  name         TEXT,                       -- e.g. "Push Day", "Leg Day"
  performed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes        TEXT,
  ai_raw_text  TEXT,                       -- original voice/text input for AI replay
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workouts_user_performed
  ON workouts(user_id, performed_at DESC);

ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns workouts" ON workouts;
DROP POLICY IF EXISTS "User owns workouts" ON workouts;
CREATE POLICY "User owns workouts" ON workouts
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 3. Workout Sets (each set within a workout) ───────────────────
-- AI-ready flat table — future LLM parsers can map natural language
-- ("Bench was 70kg for 5, then 72.5kg for 3") onto these exact columns.
CREATE TABLE IF NOT EXISTS workout_sets (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workout_id  UUID NOT NULL REFERENCES workouts(id)  ON DELETE CASCADE,
  exercise_id UUID NOT NULL REFERENCES exercises(id) ON DELETE RESTRICT,
  user_id     UUID NOT NULL DEFAULT auth.uid(),
  set_order   INT NOT NULL DEFAULT 1,
  weight_kg   NUMERIC(7, 2) NOT NULL CHECK (weight_kg >= 0),
  reps        INT NOT NULL CHECK (reps > 0),
  rpe         NUMERIC(3, 1) CHECK (rpe IS NULL OR rpe BETWEEN 1 AND 10),
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workout_sets_workout  ON workout_sets(workout_id);
CREATE INDEX IF NOT EXISTS idx_workout_sets_exercise ON workout_sets(exercise_id);
CREATE INDEX IF NOT EXISTS idx_workout_sets_user_exercise_created
  ON workout_sets(user_id, exercise_id, created_at DESC);

ALTER TABLE workout_sets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns workout sets" ON workout_sets;
DROP POLICY IF EXISTS "User owns workout sets" ON workout_sets;
CREATE POLICY "User owns workout sets" ON workout_sets
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 4. Weight entries (body weight log) ──────────────────────────
CREATE TABLE IF NOT EXISTS weight_entries (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL DEFAULT auth.uid(),
  weight_kg   NUMERIC(5, 2) NOT NULL CHECK (weight_kg > 0),
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_weight_entries_user_recorded
  ON weight_entries(user_id, recorded_at DESC);

ALTER TABLE weight_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns weight entries" ON weight_entries;
DROP POLICY IF EXISTS "User owns weight entries" ON weight_entries;
CREATE POLICY "User owns weight entries" ON weight_entries
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 5. Weight target (one row per user) ──────────────────────────
CREATE TABLE IF NOT EXISTS weight_target (
  user_id   UUID PRIMARY KEY DEFAULT auth.uid(),
  target_kg NUMERIC(5, 2) NOT NULL CHECK (target_kg > 0),
  set_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes     TEXT
);

ALTER TABLE weight_target ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns weight target" ON weight_target;
DROP POLICY IF EXISTS "User owns weight target" ON weight_target;
CREATE POLICY "User owns weight target" ON weight_target
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 6. Physique photos ───────────────────────────────────────────
-- Image bytes live in a private Supabase Storage bucket (`physique-photos`).
-- This table records ONE row per photo — keeps ordering, deletes, and
-- before/after queries simple.
CREATE TABLE IF NOT EXISTS physique_photos (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL DEFAULT auth.uid(),
  taken_at      DATE NOT NULL,
  pose_type     TEXT CHECK (pose_type IN ('front','back','side','other')),
  photo_path    TEXT NOT NULL,             -- "{user_id}/{uuid}.jpg" inside the bucket
  body_weight_kg NUMERIC(5, 2),
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_physique_photos_user_taken
  ON physique_photos(user_id, taken_at DESC);

ALTER TABLE physique_photos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns physique photos" ON physique_photos;
DROP POLICY IF EXISTS "User owns physique photos" ON physique_photos;
CREATE POLICY "User owns physique photos" ON physique_photos
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 7. Sleep entries ─────────────────────────────────────────────
-- `hours` is GENERATED from bedtime → wake_time so the UI never has to
-- compute it.
CREATE TABLE IF NOT EXISTS sleep_entries (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL DEFAULT auth.uid(),
  sleep_date DATE NOT NULL,
  bedtime    TIMESTAMPTZ NOT NULL,
  wake_time  TIMESTAMPTZ NOT NULL,
  hours      NUMERIC(4, 2) GENERATED ALWAYS AS
              (EXTRACT(EPOCH FROM (wake_time - bedtime)) / 3600.0) STORED,
  quality    SMALLINT CHECK (quality IS NULL OR quality BETWEEN 1 AND 5),
  notes      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sleep_entries_user_date
  ON sleep_entries(user_id, sleep_date DESC);

ALTER TABLE sleep_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns sleep entries" ON sleep_entries;
DROP POLICY IF EXISTS "User owns sleep entries" ON sleep_entries;
CREATE POLICY "User owns sleep entries" ON sleep_entries
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 8. Daily check-ins (minimal — sleep + workout + notes) ──────
CREATE TABLE IF NOT EXISTS daily_checkins (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL DEFAULT auth.uid(),
  checkin_date DATE NOT NULL,
  sleep_id     UUID REFERENCES sleep_entries(id) ON DELETE SET NULL,
  workout_id   UUID REFERENCES workouts(id)    ON DELETE SET NULL,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT  uq_daily_checkins_user_date UNIQUE (user_id, checkin_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_checkins_user_date
  ON daily_checkins(user_id, checkin_date DESC);

ALTER TABLE daily_checkins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns daily checkins" ON daily_checkins;
DROP POLICY IF EXISTS "User owns daily checkins" ON daily_checkins;
CREATE POLICY "User owns daily checkins" ON daily_checkins
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ─── 9. Milestones (manual + auto-generated flashbacks) ───────────
-- Manual milestones are user-created. Auto milestones will be written
-- by the future Flashback engine as significant deltas are detected.
CREATE TABLE IF NOT EXISTS milestones (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL DEFAULT auth.uid(),
  kind         TEXT NOT NULL CHECK (kind IN ('auto', 'manual')),
  title        TEXT NOT NULL,
  description  TEXT,
  achieved_at  TIMESTAMPTZ NOT NULL,
  related_data JSONB,                       -- e.g. { exercise: 'bench', lifts: [...] }
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_milestones_user_achieved
  ON milestones(user_id, achieved_at DESC);

ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User owns milestones" ON milestones;
DROP POLICY IF EXISTS "User owns milestones" ON milestones;
CREATE POLICY "User owns milestones" ON milestones
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- =====================================================================
-- Storage bucket for physique photos
-- =====================================================================
-- Create the private bucket (run ONCE in Supabase Dashboard → Storage,
-- or uncomment the SQL below in a fresh project). Path convention:
--   {user_id}/{photo_id}.{ext}
-- The RLS policy on storage.objects restricts access so users can only
-- read/write objects whose first path segment is their own auth.uid().
-- =====================================================================

-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('physique-photos', 'physique-photos', false)
-- ON CONFLICT (id) DO NOTHING;

-- DROP POLICY IF EXISTS "User owns photo objects read"   ON storage.objects;
-- DROP POLICY IF EXISTS "User owns photo objects insert"  ON storage.objects;
-- DROP POLICY IF EXISTS "User owns photo objects update"  ON storage.objects;
-- DROP POLICY IF EXISTS "User owns photo objects delete"  ON storage.objects;
--
-- CREATE POLICY "User owns photo objects read"   ON storage.objects
--   FOR SELECT TO authenticated
--   USING (bucket_id = 'physique-photos'
--          AND auth.uid()::text = (storage.foldername(name))[1]);
-- CREATE POLICY "User owns photo objects insert"  ON storage.objects
--   FOR INSERT TO authenticated
--   WITH CHECK (bucket_id = 'physique-photos'
--               AND auth.uid()::text = (storage.foldername(name))[1]);
-- CREATE POLICY "User owns photo objects update"  ON storage.objects
--   FOR UPDATE TO authenticated
--   USING (bucket_id = 'physique-photos'
--          AND auth.uid()::text = (storage.foldername(name))[1]);
-- CREATE POLICY "User owns photo objects delete"  ON storage.objects
--   FOR DELETE TO authenticated
--   USING (bucket_id = 'physique-photos'
--          AND auth.uid()::text = (storage.foldername(name))[1]);


-- ──── lib\supabase-gym-migration.sql ────

-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- Quick post-workout gym logging table.
-- One row = one exercise logged after a workout session.
-- Stores 2 working sets per exercise + optional warm-up.

CREATE TABLE IF NOT EXISTS workout_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid() NOT NULL,
  workout_type TEXT NOT NULL CHECK (workout_type IN ('upper', 'lower', 'push', 'pull', 'legs', 'full')),
  exercise TEXT NOT NULL,
  set1_weight DECIMAL(8,2),
  set1_reps INTEGER CHECK (set1_reps IS NULL OR set1_reps > 0),
  set1_failure BOOLEAN DEFAULT true,
  set2_weight DECIMAL(8,2),
  set2_reps INTEGER CHECK (set2_reps IS NULL OR set2_reps > 0),
  set2_failure BOOLEAN DEFAULT true,
  warmup TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for time-series queries
CREATE INDEX IF NOT EXISTS idx_workout_logs_user ON workout_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_workout_logs_created_at ON workout_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_workout_logs_workout_type ON workout_logs(workout_type);

-- Enable Row Level Security
ALTER TABLE workout_logs ENABLE ROW LEVEL SECURITY;

-- Drop old policies if any
DROP POLICY IF EXISTS "User owns data" ON workout_logs;

-- User-scoped RLS policy
DROP POLICY IF EXISTS "User owns data" ON workout_logs;
CREATE POLICY "User owns data" ON workout_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ──── lib\supabase-workout-summary-migration.sql ────

-- =====================================================================
-- ORION: Workout summary model — additive migration
-- =====================================================================
-- Apply AFTER supabase-fitness-migration.sql.
--
-- Purpose: switch the logging UI from "one row per set" to "one row per
-- (workout, exercise)" where the row stores the BEST working set
-- (weight, optional reps) plus the count of working sets. Legacy rows
-- are preserved unchanged; new entries fill the new columns.
--
-- Why additive (not destructive):
--   1. Legacy rows in workout_sets have `reps` always set, so dropping
--      NOT NULL on `reps` is safe and non-destructive — existing data
--      is unaffected.
--   2. Adding working_sets_count as NULLABLE keeps legacy rows valid
--      (NULL = "we don't know, treat as 1 set for analytics").
--   3. Future Hevy / voice / AI parsers can drop into the same table
--      with full per-set detail OR with summary rows; both shapes
--      are now first-class.
--
-- Rollback:
--   ALTER TABLE workout_sets DROP COLUMN IF EXISTS working_sets_count;
--   ALTER TABLE workout_sets ALTER COLUMN reps SET NOT NULL;
-- (safe — losing the new column does not destroy data; only the summary
--  numbers are gone. The NOT NULL re-add will fail if any NULL reps
--  exist; delete or backfill those rows first.)
-- =====================================================================


-- ─── 1. Make `reps` optional (best working set reps can be skipped) ──
ALTER TABLE workout_sets
  ALTER COLUMN reps DROP NOT NULL;


-- ─── 2. Add the working-sets-count column (legacy rows stay NULL) ────
ALTER TABLE workout_sets
  ADD COLUMN IF NOT EXISTS working_sets_count INTEGER
  CHECK (working_sets_count IS NULL OR working_sets_count > 0);

-- No backfill: legacy multi-row workouts stay with working_sets_count
-- = NULL. `effectiveSetCount(NULL) = 1` (lib/fitness/strength.ts),
-- so the analytics volume formula `Σ(weight × reps × 1)` summed over
-- all legacy rows of a multi-set exercise yields the correct total
-- (each row = one set). The alternative — stamping every sibling row
-- with the group count and multiplying — would 3× the volume for any
-- user that pre-dated this migration.


-- ─── 3. Index to speed up "latest summary row per (user, exercise)" ───
CREATE INDEX IF NOT EXISTS idx_workout_sets_user_exercise_summary
  ON workout_sets(user_id, exercise_id, weight_kg DESC)
  WHERE working_sets_count IS NOT NULL;


-- ─── 4. RLS already covers this table from prior migration ───────────
-- The "User owns workout sets" policy from supabase-fitness-migration.sql
-- is FOR ALL (SELECT / INSERT / UPDATE / DELETE) — fully covers the
-- new column. Re-affirm instead of re-creating to avoid DeadlockRisk:
-- (we learned from the earlier incident that iterating pg_policies is
-- unsafe under multiple statements in one transaction).

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename  = 'workout_sets'
       AND policyname = 'User owns workout sets'
  ) THEN
    ALTER TABLE workout_sets ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "User owns workout sets" ON workout_sets
      FOR ALL TO authenticated
      USING      (user_id = auth.uid())
      WITH CHECK (user_id = auth.uid());
  END IF;
END $$;


-- ─── 5. Force PostgREST to refresh its schema cache ──────────────────
-- After this migration, the new column is queryable in the browser
-- without manually re-deploying the PostgREST schema. Caveat: NOTIFY
-- only fires on COMMIT — if any statement above errors, the NOTIFY is
-- silently dropped. The smoke-test SELECT immediately below is the
-- durable "did the columns land?" answer regardless.
NOTIFY pgrst, 'reload schema';


-- ─── 6. In-script smoke test (renders immediately in Results tab) ────
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'workout_sets'
  AND column_name  IN ('working_sets_count', 'reps', 'weight_kg')
ORDER BY column_name;

-- ─── Verification (run as a separate query after the block above) ────
--
-- Confirm the new column + nullable reps:
--   SELECT column_name, data_type, is_nullable
--     FROM information_schema.columns
--    WHERE table_schema = 'public'
--      AND table_name   = 'workout_sets'
--      AND column_name IN ('reps', 'working_sets_count')
--    ORDER BY column_name;
--
-- Quick sanity: NULL reps (user logged weight only) + NON-NULL weight:
--   SELECT COUNT(*) AS weight_only_logs
--     FROM workout_sets
--    WHERE reps IS NULL AND weight_kg > 0;
--
-- Legacy row distribution (no NULL backfill on this run):
--   SELECT
--     COUNT(*) FILTER (WHERE working_sets_count IS NULL) AS legacy_null,
--     COUNT(*) FILTER (WHERE working_sets_count IS NOT NULL) AS explicit
--   FROM workout_sets;


-- ──── lib\supabase-health-migration.sql ────

-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- Health Dashboard tables — stores RAW data only, no derived/computed fields.
-- All tables include user_id for RLS scoping.

-- 1. Sleep Logs
CREATE TABLE IF NOT EXISTS sleep_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  sleep_start TIMESTAMPTZ NOT NULL,
  sleep_end TIMESTAMPTZ NOT NULL,
  quality INTEGER NOT NULL CHECK (quality >= 1 AND quality <= 10),
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Activity Logs
CREATE TABLE IF NOT EXISTS activities (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  activity_type TEXT NOT NULL,
  duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
  intensity TEXT NOT NULL CHECK (intensity IN ('low', 'medium', 'high')),
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Gym Logs (structured workouts)
CREATE TABLE IF NOT EXISTS gym_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  exercise TEXT NOT NULL,
  sets INTEGER NOT NULL CHECK (sets > 0),
  reps INTEGER NOT NULL CHECK (reps > 0),
  weight DECIMAL(8,2) NOT NULL CHECK (weight >= 0),
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Physique Logs (body measurements & progress photos)
CREATE TABLE IF NOT EXISTS physique_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  bodyweight DECIMAL(5,2),
  photo_url TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Nutrition / Recovery Logs
CREATE TABLE IF NOT EXISTS nutrition_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  water_ml INTEGER DEFAULT 0 CHECK (water_ml >= 0),
  caffeine_mg INTEGER DEFAULT 0 CHECK (caffeine_mg >= 0),
  caffeine_time TIMESTAMPTZ,
  creatine_taken BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6. Manual Inputs (real-time state tracking for AI calibration)
CREATE TABLE IF NOT EXISTS manual_inputs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  energy_level INTEGER NOT NULL CHECK (energy_level >= 1 AND energy_level <= 10),
  focus_level INTEGER NOT NULL CHECK (focus_level >= 1 AND focus_level <= 10),
  stress_level INTEGER NOT NULL CHECK (stress_level >= 1 AND stress_level <= 10),
  soreness_level INTEGER NOT NULL CHECK (soreness_level >= 1 AND soreness_level <= 10),
  mood TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for time-series queries
CREATE INDEX IF NOT EXISTS idx_sleep_logs_user ON sleep_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_sleep_logs_start ON sleep_logs(sleep_start);
CREATE INDEX IF NOT EXISTS idx_sleep_logs_end ON sleep_logs(sleep_end);
CREATE INDEX IF NOT EXISTS idx_activities_user ON activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_created_at ON activities(created_at);
CREATE INDEX IF NOT EXISTS idx_activities_type ON activities(activity_type);
CREATE INDEX IF NOT EXISTS idx_gym_logs_user ON gym_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_gym_logs_created_at ON gym_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_gym_logs_exercise ON gym_logs(exercise);
CREATE INDEX IF NOT EXISTS idx_physique_logs_user ON physique_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_physique_logs_created_at ON physique_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_nutrition_logs_user ON nutrition_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_nutrition_logs_created_at ON nutrition_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_manual_inputs_user ON manual_inputs(user_id);
CREATE INDEX IF NOT EXISTS idx_manual_inputs_created_at ON manual_inputs(created_at);

-- Enable Row Level Security
ALTER TABLE sleep_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE physique_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE nutrition_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE manual_inputs ENABLE ROW LEVEL SECURITY;

-- Drop old public-access policies before creating user-scoped ones
DROP POLICY IF EXISTS "Public access" ON sleep_logs;
DROP POLICY IF EXISTS "Public access" ON activities;
DROP POLICY IF EXISTS "Public access" ON gym_logs;
DROP POLICY IF EXISTS "Public access" ON physique_logs;
DROP POLICY IF EXISTS "Public access" ON nutrition_logs;
DROP POLICY IF EXISTS "Public access" ON manual_inputs;

-- User-scoped RLS policies (rows must belong to the authenticated user)
DROP POLICY IF EXISTS "User owns data" ON sleep_logs;
CREATE POLICY "User owns data" ON sleep_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON activities;
CREATE POLICY "User owns data" ON activities
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON gym_logs;
CREATE POLICY "User owns data" ON gym_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON physique_logs;
CREATE POLICY "User owns data" ON physique_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON nutrition_logs;
CREATE POLICY "User owns data" ON nutrition_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns data" ON manual_inputs;
CREATE POLICY "User owns data" ON manual_inputs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ──── lib\supabase-tasks-migration.sql ────

-- ============================================================
-- MIGRATION: Create tasks table for the To-Do list
-- ============================================================
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- after the habits fix migration has been applied.
-- ============================================================

-- ============================================================
-- 1. Create tasks table
-- ============================================================
CREATE TABLE IF NOT EXISTS tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid() NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
  scheduled_for DATE NOT NULL,
  duration_minutes INTEGER,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_scheduled_for ON tasks(scheduled_for);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);

-- ============================================================
-- 2. Enable RLS
-- ============================================================
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 3. Drop stale policies (safe to re-run)
-- ============================================================
DROP POLICY IF EXISTS "Public access" ON tasks;
DROP POLICY IF EXISTS "User owns data" ON tasks;

-- ============================================================
-- 4. Create user-scoped RLS policies
-- ============================================================
DROP POLICY IF EXISTS "User owns data" ON tasks;
CREATE POLICY "User owns data" ON tasks
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- ──── lib\supabase-finance-migration.sql ────

-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- v2 — Merged ISA/JISA into single type with is_jisa flag + contribution tracking

-- 1. Accounts table
CREATE TABLE IF NOT EXISTS accounts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('savings', 'cash', 'investment', 'isa')),
  balance DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  interest_rate DECIMAL(5, 2),
  is_jisa BOOLEAN DEFAULT false,
  birth_date DATE,
  contribution_ytd DECIMAL(12, 2) DEFAULT 0.00,
  contribution_year INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Transactions table
CREATE TABLE IF NOT EXISTS transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense', 'transfer')),
  amount DECIMAL(12, 2) NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  transfer_to_account_id UUID REFERENCES accounts(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS idx_accounts_user_id ON accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date DESC);

-- 4. Enable RLS
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- 5. Drop old policies before creating new ones
DROP POLICY IF EXISTS "User owns accounts" ON accounts;
DROP POLICY IF EXISTS "User owns transactions" ON transactions;

-- 6. RLS policies — rows scoped to the authenticated user
DROP POLICY IF EXISTS "User owns accounts" ON accounts;
CREATE POLICY "User owns accounts" ON accounts
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User owns transactions" ON transactions;
CREATE POLICY "User owns transactions" ON transactions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 7. Migration helper: convert old JISA-type accounts to new format
-- Run this once if you had existing 'JISA' type accounts:
-- UPDATE accounts SET type = 'isa', is_jisa = true WHERE type = 'JISA';
-- UPDATE accounts SET type = 'isa' WHERE type = 'ISA';


-- ──── lib\supabase-future-transactions-migration.sql ────

-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- Adds future_transactions table for persisting projected events

-- 1. Future transactions table
-- Stores income/expense/transfer events scheduled at a future age for projection purposes
CREATE TABLE IF NOT EXISTS future_transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(),
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE NOT NULL,
  age INTEGER NOT NULL CHECK (age > 0),
  description TEXT NOT NULL,
  amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  to_account_id UUID REFERENCES accounts(id) ON DELETE SET NULL,
  transfer_mode TEXT CHECK (transfer_mode IN ('fixed', 'percent', 'above_threshold')),
  transfer_value DECIMAL(12, 2),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Indexes
CREATE INDEX IF NOT EXISTS idx_future_transactions_user_id ON future_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_future_transactions_age ON future_transactions(age);

-- 3. Enable RLS
ALTER TABLE future_transactions ENABLE ROW LEVEL SECURITY;

-- 4. Drop old policies before creating new ones
DROP POLICY IF EXISTS "User owns future transactions" ON future_transactions;

-- 5. RLS policy — rows scoped to the authenticated user
DROP POLICY IF EXISTS "User owns future transactions" ON future_transactions;
CREATE POLICY "User owns future transactions" ON future_transactions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ──── lib\supabase-time-management-migration.sql ────

-- Time Management — Phase 1 schema foundation
--
-- Additions:
--   1. habits.duration_minutes — optional estimated duration per habit.
--      The "smart habits" logic (curfew-based AVAILABLE/LOCKED states
--      and live recommendations) reads this column to decide whether a
--      habit fits in the remaining free time before curfew.
--   2. habits.priority — optional integer 0-3 (0 = no priority, 1 = low,
--      2 = medium, 3 = high). Drives ordering in the recommendations
--      banner; higher priority = appears earlier.
--
-- New table:
--   3. calendar_events — fixed commitments ONLY (school, tennis,
--      football, appointments, holidays, manually created events).
--      Habits are intentionally NOT stored here — they remain
--      checkbox-based daily priorities; the calendar is reserved for
--      blocks that genuinely consume time.

-- ─── habits: add duration + priority ───────────────────────────────

ALTER TABLE habits
  ADD COLUMN IF NOT EXISTS duration_minutes INTEGER
    CHECK (duration_minutes IS NULL OR duration_minutes > 0),
  ADD COLUMN IF NOT EXISTS priority SMALLINT
    DEFAULT 0
    CHECK (priority BETWEEN 0 AND 3);

COMMENT ON COLUMN habits.duration_minutes IS
  'Estimated minutes to complete the habit. Drives curfew fit analysis.';
COMMENT ON COLUMN habits.priority IS
  '0 = no priority, 1 = low, 2 = medium, 3 = high. Used for recommendation ordering.';

-- ─── calendar_events: fixed commitments only ────────────────────────

CREATE TABLE IF NOT EXISTS calendar_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ NOT NULL,
  -- Optional visual + placement metadata
  location TEXT,
  notes TEXT,
  color TEXT,                -- e.g. 'bg-rose-500' or null for default
  -- Used to distinguish fixed manual blocks from auto-imported ones
  -- (Google Calendar, ICS, etc.) — Phase 4.
  source TEXT DEFAULT 'manual',
  CONSTRAINT calendar_events_end_after_start CHECK (end_at > start_at),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS calendar_events_user_start_idx
  ON calendar_events (user_id, start_at);

ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read their own calendar_events" ON calendar_events;
DROP POLICY IF EXISTS "Users read their own calendar_events" ON calendar_events;
CREATE POLICY "Users read their own calendar_events" ON calendar_events
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users insert their own calendar_events" ON calendar_events;
DROP POLICY IF EXISTS "Users insert their own calendar_events" ON calendar_events;
CREATE POLICY "Users insert their own calendar_events" ON calendar_events
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users update their own calendar_events" ON calendar_events;
DROP POLICY IF EXISTS "Users update their own calendar_events" ON calendar_events;
CREATE POLICY "Users update their own calendar_events" ON calendar_events
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users delete their own calendar_events" ON calendar_events;
DROP POLICY IF EXISTS "Users delete their own calendar_events" ON calendar_events;
CREATE POLICY "Users delete their own calendar_events" ON calendar_events
  FOR DELETE USING (auth.uid() = user_id);

